[package]
name = "xrc_mock"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
ic-xrc-types = "1.2.0"
candid = "0.10"
ic-cdk = "0.16"
serde = "1.0.197"
serde_derive = "1.0.197"
ic-cdk-macros = "0.17.0"