mod stable_memory;
pub mod general;
pub mod xrc_mock;
pub use xrc_mock::get_icp_rate;
pub use general::*;
use candid::Principal;
use icrc_ledger_types::icrc1::account::Account;
use icrc_ledger_types::icrc1::transfer::NumTokens;
use icrc_ledger_types::icrc1::transfer::BlockIndex;
use candid::Nat;
ic_cdk::export_candid!();
